# Proposal

## Research topic

The first objective of this project is to highlight the current situation and historical trends. This shows us where we are, and where we have come from. These are the aspects we want to present:

* How have the world and regional populations evolved over the past 5 decades?
* Which regions have the youngest / oldest population?
* Which regions have had the highest / lowest birth rate, death rate, and population growth?
* How have birth rates changed cross-sectionally by country?
* How has world longevity evolved over the past decades?
* Is there any gender asymmetry in the birth rate and longevity?

The second objective of this project is to look for patterns and relationships among demographic and other factors. Hopefully this can reveal some hidden and intrinsic logics, and provide us with more profound understandings of world demographics. These are the questions we want to answer via visualization:

* How do other demographic factors affect birth rate?
* How do non-demographic factors (economic, healthcare, and education) affect birth rate?
* How does income category affect longevity?
* How does income category affect death rates of difference causes?
* How do labor force and quality affect economic development?


## Data availability

To answer the questions in the previous section, we need periodic data in various demographic and non-demographic statistics, broken down into regions and countries. The data should cover fields such as:
* Demographic: population by gender and age group, birth rate, death rate, life expectancy
* Economic: gdp per capita, income per capita, economic growth
* Social: education, medical services
* Policies:

A reliable data source that serves our purposes is the World Bank’s database “Health Nutrition and Population Statistics” (https://databank.worldbank.org/source/health-nutrition-and-population-statistics). They maintain comprehensive demographic and non-demographic data covering the aspects mentioned above.

The data can be downloaded as spreadsheet from the interface, by specifying filters on country, series (field), and year. Data can be imported to RStudio from the spreadsheet.


## Plots plan


**Current situation and historical trends**

**1 How have the world and regional populations evolved over the past 5 decades?**  
Line chart:  
x = Year  
y = Population total (world, by region)

Mosaic plot:  
Population total by region (% of world) ~ Year, Region

**2 Which regions have the youngest / oldest population?**  
Grouped barcharts (2020, by region):   
y = median age (need to calculate)  
x groups = 1980, 1990, 2000, 2010, 2020  
x in each group = regions

Population pyramid:  
https://klein.uk/teaching/viz/datavis-pyramids/

**3 Which regions have had the highest / lowest birth rate, death rate, and population growth?**  
Cleveland dot plot (1980):  
x = Birth rate x 10, Death rate x 10, Population growth (annual %)  
y = region
  
Cleveland dot plot (2020):  
Same

**4 How have birth rates changed cross-sectionally by country?**  
Scatter plot:  
x = birth rate by country in 1980  
y = birth rate by country in 2020

**5 How has world longevity evolved over the past decades?**  
Ridgeline plot (by country):  
x = Life expectancy at birth, total (years)  
y = 1980, 1990, 2000, 2010, 2020

**6 Is there any gender asymmetry in the birth rate and longevity? (Yuxiao)**  
Sex ratio at birth (male births per female births)  
GNI per capita

**Pattern and relationships**

**7 How do other demographic factors affect birth rate?**  
Scatter plots (by country, 2020):  
y = birth rate  
x = Population ages 15-19, female (% of female population) + …  
+ Population ages 45-49, female (% of female population)  
  
y = birth rate  
x = Age at first marriage, female


**8 How do non-demographic factors (economic, healthcare, and education) affect birth rate?**  
PCA (or parallel coordinate plot) (by country, 2020):  
Birth rate  
GNI per capita  
Labor force, female (% of total labor force)  
Domestic general government health expenditure (% of GDP)  
Public spending on education, total (% of GDP)  
Literacy rate, adult total (% of people ages 15 and above)  
School enrollment, tertiary, female (% gross)  

**9 How does income category affect longevity?**  
Ridgeline plots x 5 (1980, 1990, 2000, 2010, 2020) (income table):  
x = Life expectancy at birth, total (years)  
y = income category [income table]

**10 How does income category affect death rates of difference causes?**  
Heat map (or mosaic plot) (income table, 2020):  
vertical cut = income category  
horizontal cut =  
Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)  
Cause of death, by injury (% of total)  
Cause of death, by non-communicable diseases (% of total)

**11 How do labor force and quality affect economic development?**  
Parallel coordinate plot (by country):  
2020 divided by 2000:  
GNI per capita growth  
  
2000:  
Labor force total / Population total  
Urban population (% of total population)  
Human capital index (HCI) (scale 0-1)  
Literacy rate, adult total (% of people ages 15 and above)  
School enrollment, secondary (% gross)  
School enrollment, tertiary (% gross)  

