# Results

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(data.table)
library(ggplot2)
library(forcats)
```


```{r}
Stats_by_Country_1972_1996 <- read_csv("data/Stats_by_Country_1972-1996.csv", na = "NA")
Stats_by_Country_1997_2021 <- read_csv("data/Stats_by_Country_1997-2021.csv", na = "NA")
Stats_by_Income_1972_2021 <- read_csv("data/Stats_by_Income_1972-2021.csv", na = "NA")
Stats_by_Region_1972_2021 <- read_csv("data/Stats_by_Region_1972-2021.csv", na = "NA")
```

###Region data

```{r}
# Rename Columns
setnames((Stats_by_Region_1972_2021), old = c("Series Name","Series Code", "Country Name", "Country Code"), new = c("SeN", "SeC", "CoN", "CoC"))
colnames(Stats_by_Region_1972_2021) <- substring(colnames(Stats_by_Region_1972_2021), 1, 4)
```

###Income data
```{r}
# Rename Columns
setnames((Stats_by_Income_1972_2021), old = c("Series Name","Series Code", "Country Name", "Country Code"), new = c("SeN", "SeC", "CoN", "CoC"))
colnames(Stats_by_Income_1972_2021) <- substring(colnames(Stats_by_Income_1972_2021), 1, 4)
```

###Country data
```{r}
common_col_names <- intersect(names(Stats_by_Country_1972_1996), names(Stats_by_Country_1997_2021))
Stats_by_Country_1972_2021 <- merge(Stats_by_Country_1972_1996, Stats_by_Country_1997_2021, all.x = TRUE)
```

```{r}
# Rename Columns
setnames((Stats_by_Country_1972_2021), old = c("Series Name","Series Code", "Country Name", "Country Code"), new = c("SeN", "SeC", "CoN", "CoC"))
colnames(Stats_by_Country_1972_2021) <- substring(colnames(Stats_by_Country_1972_2021), 1, 4)
```



```{r}
##################################
##########  Question 2  ##########
##################################

Q2_fields = c('SP.POP.0014.TO.ZS', 'SP.POP.1564.TO.ZS', 'SP.POP.65UP.TO.ZS')

AgeGroup_Region <- Stats_by_Region_1972_2021 %>%
  filter(SeC %in% Q2_fields, ! CoC %in% c('EUU', 'EMU')) %>%
  select(c('SeC', 'SeN', 'CoN', '1980', '1990', '2000', '2010', '2021')) %>%
  pivot_longer(cols = !c('SeC', 'SeN', 'CoN'), names_to = 'Year', values_to = 'Percent')

# Convert and sort
AgeGroup_Region$Percent <- as.numeric(AgeGroup_Region$Percent)
young_sorted = AgeGroup_Region[AgeGroup_Region$SeC == 'SP.POP.0014.TO.ZS'
                               & AgeGroup_Region$Year == '2021', c('CoN', 'Percent')] %>%
  arrange(Percent)
AgeGroup_Region$CoN = factor(AgeGroup_Region$CoN, levels = young_sorted$CoN)

ggplot(data = AgeGroup_Region) +
  geom_col(aes(x = Percent, y = CoN,  fill = SeN)) +
  facet_wrap(~ Year) +
  labs(title = 'Population Age Groups by Region', x = '% of Total Population', y = 'Region') +
  scale_fill_manual(labels = c('0-14', '15-64', '65 and above'), values = c('#619CFF', '#00BA38', '#F8766D')) +
  scale_x_reverse() +
  guides(fill = guide_legend('Age Group'))

ggplot(data = AgeGroup_Region) +
  geom_col(aes(x = Percent, y = fct_rev(Year),  fill = SeN)) +
  facet_wrap(~ CoN) +
  labs(title = 'Population Age Groups by Region', x = '% of Total Population', y = 'Year') +
  scale_fill_manual(labels = c('0-14', '15-64', '65 and above'), values = c('#619CFF', '#00BA38', '#F8766D')) +
  scale_x_reverse() +
  guides(fill = guide_legend('Age Group'))
```



```{r}
##################################
##########  Question 6  ##########
##################################

# Birth by gender data
GenderBirth_Income <- Stats_by_Income_1972_2021 %>%
  filter(SeC == 'SP.POP.BRTH.MF') %>%
  select(c('SeC', 'SeN', 'CoN', '2020'))
GenderBirth_Region <- Stats_by_Region_1972_2021 %>%
  filter(SeC == 'SP.POP.BRTH.MF') %>%
  select(c('SeC', 'SeN', 'CoN', '2020'))
GenderBirth_Country <- Stats_by_Country_1972_2021 %>%
  filter(SeC == 'SP.POP.BRTH.MF') %>%
  select(c('SeC', 'SeN', 'CoN', '2020'))
setnames((GenderBirth_Income), old = c("2020"), new = c("Value"))
setnames((GenderBirth_Region), old = c("2020"), new = c("Value"))
setnames((GenderBirth_Country), old = c("2020"), new = c("Value"))
GenderBirth_Income$Value <- as.numeric(GenderBirth_Income$Value)
GenderBirth_Region$Value <- as.numeric(GenderBirth_Region$Value)
GenderBirth_Country$Value <- as.numeric(GenderBirth_Country$Value)

GenderBirth_Country <- GenderBirth_Country %>%
  drop_na() %>%
  arrange(desc(Value))
nrow = dim(GenderBirth_Country)[1]
GenderBirth_Country <- bind_rows(GenderBirth_Country[1:10,], GenderBirth_Country[(nrow - 9):nrow,])

GenderBirth_Income$Type <- 'by Income Category'
GenderBirth_Region$Type <- 'by Region'
GenderBirth_Country$Type <- 'Top Countries'
GenderBirth <- bind_rows(GenderBirth_Income, GenderBirth_Region, GenderBirth_Country)

# Longevity by gender data
GenderLongevity_Income <- Stats_by_Income_1972_2021 %>%
  filter(SeC %in% c('SP.DYN.LE00.MA.IN', 'SP.DYN.LE00.FE.IN')) %>%
  select(c('SeC', 'SeN', 'CoN', '2020'))
GenderLongevity_Region <- Stats_by_Region_1972_2021 %>%
  filter(SeC %in% c('SP.DYN.LE00.MA.IN', 'SP.DYN.LE00.FE.IN')) %>%
  select(c('SeC', 'SeN', 'CoN', '2020'))
GenderLongevity_Country <- Stats_by_Country_1972_2021 %>%
  filter(SeC %in% c('SP.DYN.LE00.MA.IN', 'SP.DYN.LE00.FE.IN')) %>%
  select(c('SeC', 'SeN', 'CoN', '2020'))
setnames((GenderLongevity_Income), old = c("2020"), new = c("Value"))
setnames((GenderLongevity_Region), old = c("2020"), new = c("Value"))
setnames((GenderLongevity_Country), old = c("2020"), new = c("Value"))
GenderLongevity_Income$Value <- as.numeric(GenderLongevity_Income$Value)
GenderLongevity_Region$Value <- as.numeric(GenderLongevity_Region$Value)
GenderLongevity_Country$Value <- as.numeric(GenderLongevity_Country$Value)

GenderLongevity_Income$Type <- 'by Income Category'
GenderLongevity_Region$Type <- 'by Region'
GenderLongevity <- bind_rows(GenderLongevity_Income, GenderLongevity_Region)

GenderLongevityDiff_Country = GenderLongevity_Country %>%
  pivot_wider(id_cols = CoN, names_from = SeC, values_from = Value) %>%
  mutate(Diff = SP.DYN.LE00.FE.IN - SP.DYN.LE00.MA.IN) %>%
  drop_na() %>%
  arrange(desc(Diff))
nrow = dim(GenderLongevityDiff_Country)[1]
GenderLongevityDiff_Country <- bind_rows(GenderLongevityDiff_Country[1:10,], GenderLongevityDiff_Country[(nrow - 9):nrow,])

ggplot(data = GenderBirth) +
  geom_point(aes(x = Value, y = reorder(CoN, Value)), color = '#00BA38') +
  labs(title = 'Gender Asymmetry - Birth Rate (2020)', x = 'Birth Ratio (Male/Female)', y = '') +
  facet_grid(Type ~ ., scales = 'free_y', space = 'free_y')
  # theme(legend.position = "none")

ggplot(data = GenderLongevity) +
  geom_point(aes(x = Value, y = reorder(CoN, Value), color = SeN)) +
  labs(title = 'Gender Asymmetry - Longevity (2020)', x = 'Life Expectancy', y = '') +
  facet_grid(Type ~ ., scales = 'free_y', space = 'free_y') +
  scale_color_manual(labels = c('Female', 'Male'), values = c('#F8766D', '#619CFF')) +
  guides(color = guide_legend('Gender'))

ggplot(data = GenderLongevityDiff_Country) +
  geom_point(aes(x = Diff, y = reorder(CoN, Diff)), color = '#00BA38') +
  labs(title = 'Gender Difference - Longevity (2020)', x = 'Life Expectancy (Female - Male)', y = 'Top and Bottom Countries')
  # theme(legend.position = "none")
```


```{r}
##################################
##########  Question 7  ##########
##################################

Q7_fields = c('SP.DYN.CBRT.IN', 'SP.POP.TOTL.FE.ZS', 'SP.POP.1519.FE.5Y', 'SP.POP.2024.FE.5Y',
              'SP.POP.2529.FE.5Y', 'SP.POP.3034.FE.5Y', 'SP.POP.3539.FE.5Y', 'SP.POP.4044.FE.5Y',
              'SP.POP.4549.FE.5Y')

BirthRate_ChildBearing_Country <- Stats_by_Country_1972_2021 %>%
  filter(SeC %in% Q7_fields) %>%
  select(c('SeC', 'SeN', 'CoN', 'CoC', '1980', '2020')) %>%
  pivot_longer(cols = !c('SeC', 'SeN', 'CoN', 'CoC'), names_to = 'Year', values_to = 'Value')
# Convert and sort
BirthRate_ChildBearing_Country$Value <- as.numeric(BirthRate_ChildBearing_Country$Value)

BirthRate_ChildBearing_Country = BirthRate_ChildBearing_Country %>%
  pivot_wider(id_cols = c(CoN, CoC, Year), names_from = SeC, values_from = Value) %>%
  mutate(Percent1549 = (SP.POP.1519.FE.5Y + SP.POP.2024.FE.5Y + SP.POP.2529.FE.5Y +
                                  SP.POP.3034.FE.5Y + SP.POP.3539.FE.5Y + SP.POP.4044.FE.5Y +
                                  SP.POP.4549.FE.5Y) * SP.POP.TOTL.FE.ZS / 10000) %>%
  mutate(Percent2034 = (SP.POP.2024.FE.5Y + SP.POP.2529.FE.5Y + SP.POP.3034.FE.5Y)
         * SP.POP.TOTL.FE.ZS / 10000) %>%
  drop_na()


BirthRate_AgeMarriage_Country <- Stats_by_Country_1972_2021 %>%
  filter(SeC %in% c('SP.DYN.CBRT.IN', 'SP.DYN.SMAM.FE')) %>%
  select(c('SeC', 'SeN', 'CoN', 'CoC', '2018')) %>%
  pivot_longer(cols = !c('SeC', 'SeN', 'CoN', 'CoC'), names_to = 'Year', values_to = 'Value')
# Convert and sort
BirthRate_AgeMarriage_Country$Value <- as.numeric(BirthRate_AgeMarriage_Country$Value)

BirthRate_AgeMarriage_Country = BirthRate_AgeMarriage_Country %>%
  pivot_wider(id_cols = c(CoN, CoC, Year), names_from = SeC, values_from = Value) %>%
  drop_na()

ggplot(data = BirthRate_ChildBearing_Country) +
  geom_point(aes(x = Percent2034, y = SP.DYN.CBRT.IN), color = '#619CFF', alpha = 0.7) +
  geom_text(aes(x = Percent2034, y = SP.DYN.CBRT.IN - 1, label = CoC), size = 1.5) +
  facet_wrap(~ Year) +
  labs(title = 'Birth Rate per 1000 ppl ~ % Women Age 20-34', x = 'Women Age 20-34 (% of Total Population)', y = 'Birth Rate per 1000 ppl')

ggplot(data = BirthRate_AgeMarriage_Country) +
  geom_point(aes(x = SP.DYN.SMAM.FE, y = SP.DYN.CBRT.IN), color = '#619CFF', alpha = 0.7) +
  geom_text(aes(x = SP.DYN.SMAM.FE, y = SP.DYN.CBRT.IN - 1, label = CoC), size = 1.5) +
  facet_wrap(~ Year) +
  labs(title = 'Birth Rate per 1000 ppl ~ Women Age at First Marriage', x = 'Women Age at First Marriage', y = 'Birth Rate per 1000 ppl')

```



```{r}
##################################
##########  Question 8  ##########
##################################


```
